const OPENAI_API_KEY = "AIzaSyB73LxVgqTfeVWt8L2QZSZQnaEIRG0xxK4";

import { GoogleGenerativeAI } from "https://esm.run/@google/generative-ai";

// Function to send a message
async function sendMessage() {
  try {
    const userInput = document.getElementById("user-input").value.trim();
    if (!userInput) return; // Do not send empty messages

    const chatBox = document.getElementById("chat-box");

    // Display user message
    displayMessage("You", userInput);

    // Respond with a message generated by Gemini AI
    const geminiAI = new GoogleGenerativeAI(OPENAI_API_KEY);
    const model = geminiAI.getGenerativeModel({ model: 'gemini-pro' });
    const result = await model.generateContent(userInput);
    const response = await result.response.text();
    
    // Display bot's response
    displayMessage("Bot", response);

    // Clear input field
    document.getElementById("user-input").value = "";

    // Scroll to bottom of chat box
    chatBox.scrollTop = chatBox.scrollHeight;

    // Save chat history to local storage
    saveChatHistory(chatBox.innerHTML);
  } catch (error) {
    console.error("Error:", error);
    displayMessage("Bot", "Oops! Something went wrong while processing your request. Please try again later.");
  }
}

// Function to display messages in the chat box
function displayMessage(sender, message) {
  const chatBox = document.getElementById("chat-box");
  chatBox.innerHTML += `<p><strong>${sender}:</strong> ${message}</p>`;
}

// Function to handle sending messages when Enter key is pressed
document.getElementById("user-input").addEventListener("keypress", function(event) {
  if (event.key === "Enter") {
    sendMessage();
  }
});

// Function to handle sending messages when button is clicked
document.getElementById("send-button").addEventListener("click", function() {
  sendMessage();
});

// Function to save chat history to local storage
function saveChatHistory(history) {
  localStorage.setItem("chatHistory", history);
}

// Load chat history from local storage on page load
window.onload = function() {
  const chatHistory = localStorage.getItem("chatHistory");
  const chatBox = document.getElementById("chat-box");
  if (chatHistory) {
    chatBox.innerHTML = chatHistory;
    chatBox.scrollTop = chatBox.scrollHeight;
  }
};

// Event listener for clear button click
document.getElementById("clear-button").addEventListener("click", function() {
  clearChat();
});

// Event listener for dark mode button
document.getElementById("dark").addEventListener("click", function() {
  setDarkMode();
});

// Event listener for light mode button
document.getElementById("light").addEventListener("click", function() {
  setLightMode();
});

// Function to clear chat history and local storage
function clearChat() {
  const chatBox = document.getElementById("chat-box");
  chatBox.innerHTML = "";
  localStorage.removeItem("chatHistory");
}

// // Function to set dark mode
// function setDarkMode() {
//   document.body.style.backgroundColor = "black";
//   document.getElementById("chat-box").style.backgroundColor = "black";
//   document.getElementById("user-input").style.backgroundColor = "black";
//   document.body.style.color = "white";
// }

// // Function to set light mode
// function setLightMode() {
//   document.body.style.backgroundColor = "white";
//   document.getElementById("chat-box").style.backgroundColor = "white";
//   document.getElementById("user-input").style.backgroundColor = "white";
//   document.body.style.color = "black";
// }

// Event listener for dark mode button
document.getElementById('dark').addEventListener('click', () => {
  document.body.classList.add('dark-mode');
});

// Event listener for light mode button
document.getElementById('light').addEventListener('click', () => {
  document.body.classList.remove('dark-mode');
});
